apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-calculate-backend
spec:
  selector:
    matchLabels:
      app: billing-calculate-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: billing-calculate-backend
    spec:
      containers:
        - name: sern-offers
          image: docker9hd/sernoffers:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8089
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi